"""Rewrite LLM refusals into finished flyer packages when media is generating."""

from __future__ import annotations

import re


_REFUSAL = re.compile(
    r"(cannot create (files|images)|can'?t create (files|images)|"
    r"i (currently )?cannot|unable to (create|generate|export) (images?|files?|pdf|downloadable)|"
    r"unable to generate downloadable|"
    r"step-by-step guide|use (a design tool|canva|adobe|photoshop)|"
    r"here'?s how to create|export(ing)? the flyer|instructions to create|"
    r"preferred platform|create the facebook ad on)",
    re.IGNORECASE,
)


def looks_like_media_refusal(text: str) -> bool:
    return bool(_REFUSAL.search(text or ""))


def strip_fake_download_claims(text: str) -> str:
    """Remove hallucinated download CTAs that have no real file URL."""
    if not text:
        return text
    # Drop markdown links that are not http(s)
    cleaned = re.sub(
        r"\[([^\]]*Download[^\]]*)\]\((?!https?://)[^)]*\)",
        "",
        text,
        flags=re.IGNORECASE,
    )
    drop_line = re.compile(
        r"^(?:✅\s*)?(?:files? (?:are )?ready(?: for download)?!?|"
        r"generating print-ready files now\.{0,3}|"
        r"(?:⬇️\s*)?download (?:png|pdf|mp4)|"
        r"download(?:able)? (?:png|pdf|mp4|files?))\s*$",
        re.IGNORECASE,
    )
    lines = []
    for line in cleaned.splitlines():
        stripped = line.strip()
        if drop_line.match(stripped):
            continue
        lines.append(line)
    out = "\n".join(lines)
    out = re.sub(r"\n{3,}", "\n\n", out).strip()
    return out


def strip_designer_prompt_dumps(text: str) -> str:
    """Hide Flux/Midjourney prompt lists from the user — images are generated by Replicate."""
    if not text:
        return text
    out = re.sub(
        r"\n*\*?\*?Image prompts?[^\n]*\*?\*?:?\s*\n(?:.*?\n)*?(?=\n#{1,3}\s|\n\*\*[A-Z]|\n✅|\n---|\Z)",
        "\n",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )
    out = re.sub(r"^\s*[-*]?\s*\*\*Flux:\*\*.*$", "", out, flags=re.IGNORECASE | re.MULTILINE)
    out = re.sub(
        r"^\s*[-*]?\s*\*\*Midjourney:\*\*.*$",
        "",
        out,
        flags=re.IGNORECASE | re.MULTILINE,
    )
    out = re.sub(r"^\s*Flux:\s*.+$", "", out, flags=re.IGNORECASE | re.MULTILINE)
    out = re.sub(r"^\s*Midjourney:\s*.+$", "", out, flags=re.IGNORECASE | re.MULTILINE)
    out = re.sub(
        r"^\s*This landing page is designed to .+$",
        "",
        out,
        flags=re.IGNORECASE | re.MULTILINE,
    )
    out = re.sub(r"\n{3,}", "\n\n", out).strip()
    return out


def finished_flyer_package(*, user_message: str = "") -> str:
    del user_message
    return """✅ Three flyers created — Blanco, Añejo, Collection

**Headline:** Sipping Elegance
**CTA:** Taste it
**Website:** anthonywarrenmckinzy.com

I used the official bottle photos with short overlay copy. Tell me if you want a change.
"""
