"""Rewrite LLM refusals into finished flyer packages when media is generating."""

from __future__ import annotations

import re


_REFUSAL = re.compile(
    r"(cannot create (files|images)|can'?t create (files|images)|"
    r"i (currently )?cannot|unable to (create|generate|export) (images?|files?|pdf|downloadable)|"
    r"unable to generate downloadable|"
    r"step-by-step guide|use (a design tool|canva|adobe|photoshop)|"
    r"here'?s how to create|export(ing)? the flyer|instructions to create|"
    r"preferred platform|create the facebook ad on)",
    re.IGNORECASE,
)


def looks_like_media_refusal(text: str) -> bool:
    return bool(_REFUSAL.search(text or ""))


def strip_fake_download_claims(text: str) -> str:
    """Remove hallucinated download CTAs that have no real file URL."""
    if not text:
        return text
    # Drop markdown links that are not http(s)
    cleaned = re.sub(
        r"\[([^\]]*Download[^\]]*)\]\((?!https?://)[^)]*\)",
        "",
        text,
        flags=re.IGNORECASE,
    )
    drop_line = re.compile(
        r"^(?:✅\s*)?(?:files? (?:are )?ready(?: for download)?!?|"
        r"generating print-ready files now\.{0,3}|"
        r"(?:⬇️\s*)?download (?:png|pdf|mp4)|"
        r"download(?:able)? (?:png|pdf|mp4|files?))\s*$",
        re.IGNORECASE,
    )
    lines = []
    for line in cleaned.splitlines():
        stripped = line.strip()
        if drop_line.match(stripped):
            continue
        lines.append(line)
    out = "\n".join(lines)
    out = re.sub(r"\n{3,}", "\n\n", out).strip()
    return out


def strip_designer_prompt_dumps(text: str) -> str:
    """Hide Flux/Midjourney prompt lists from the user — images are generated by Replicate."""
    if not text:
        return text
    out = re.sub(
        r"\n*\*?\*?Image prompts?[^\n]*\*?\*?:?\s*\n(?:.*?\n)*?(?=\n#{1,3}\s|\n\*\*[A-Z]|\n✅|\n---|\Z)",
        "\n",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )
    out = re.sub(r"^\s*[-*]?\s*\*\*Flux:\*\*.*$", "", out, flags=re.IGNORECASE | re.MULTILINE)
    out = re.sub(
        r"^\s*[-*]?\s*\*\*Midjourney:\*\*.*$",
        "",
        out,
        flags=re.IGNORECASE | re.MULTILINE,
    )
    out = re.sub(r"^\s*Flux:\s*.+$", "", out, flags=re.IGNORECASE | re.MULTILINE)
    out = re.sub(r"^\s*Midjourney:\s*.+$", "", out, flags=re.IGNORECASE | re.MULTILINE)
    out = re.sub(
        r"^\s*This landing page is designed to .+$",
        "",
        out,
        flags=re.IGNORECASE | re.MULTILINE,
    )
    out = re.sub(r"\n{3,}", "\n\n", out).strip()
    return out


def finished_flyer_package(*, user_message: str = "") -> str:
    black_gold = "black" in (user_message or "").lower() and "gold" in (
        user_message or ""
    ).lower()
    colors = (
        "Black `#0A0A0A` · Gold `#C9A227` · Cream `#F5F0E6`"
        if black_gold
        else "Deep agave `#0B3D2E` · Gold `#C9A227` · Cream `#F5F0E6`"
    )
    return f"""✅ Flyer created — generating print-ready PNG & PDF now

**Headline:** Blue Prince21 McKinzy
**Subheadline:** The World's First Blockchain-Native, Barrel-Backed Tequila
**Body copy:** Crafted from 100% Blue Weber agave. Additive-free. Blockchain-verified provenance. Drink it. Trade it. Own it.
**CTA:** Visit anthonywarrenmckinzy.com

**Color palette:** {colors}
**Fonts:** Cinzel (display) · Outfit (body)

**Image prompts (for the generator — no letters in the artwork):**
- **Flux:** luxury Blue Prince21 tequila bottle on {"pure black background with gold rim light" if black_gold else "agave field at golden hour"}, cinematic product photography, premium spirits ad, NO TEXT, NO WATERMARK, vertical 3:4
- **Midjourney:** same brief --ar 3:4 --stylize 250

I assumed a premium {"black & gold" if black_gold else "agave luxury"} print layout. Tell me if you want changes.
"""
