"""Upload generated bytes to Supabase Storage and return public URL."""

from __future__ import annotations

from typing import Optional, Tuple
from uuid import uuid4

import httpx

from app.core.config import Settings, get_settings
from app.database.client import get_supabase_admin
from app.utils.logging import get_logger

logger = get_logger(__name__)


class GeneratedStorage:
    def __init__(self, settings: Optional[Settings] = None) -> None:
        self._settings = settings or get_settings()
        self._db = get_supabase_admin()
        self._bucket = self._settings.generated_storage_bucket

    def public_url(self, path: str) -> str:
        base = self._settings.supabase_url.rstrip("/")
        return f"{base}/storage/v1/object/public/{self._bucket}/{path}"

    async def upload_bytes(
        self,
        *,
        user_id: str,
        data: bytes,
        ext: str,
        mime: str,
        folder: str = "media",
    ) -> Tuple[str, str]:
        safe_ext = ext.lstrip(".")
        path = f"{user_id}/{folder}/{uuid4().hex}.{safe_ext}"
        try:
            self._db.storage.from_(self._bucket).upload(
                path=path,
                file=data,
                file_options={"content-type": mime, "upsert": "true"},
            )
        except Exception as exc:
            logger.exception("generated_upload_failed", error=str(exc))
            raise
        return path, self.public_url(path)

    async def upload_from_url(
        self,
        *,
        user_id: str,
        url: str,
        ext: str,
        mime: str,
        folder: str = "media",
    ) -> Tuple[str, str, bytes]:
        async with httpx.AsyncClient(timeout=120.0, follow_redirects=True) as client:
            resp = await client.get(url)
            resp.raise_for_status()
            data = resp.content
        path, public = await self.upload_bytes(
            user_id=user_id, data=data, ext=ext, mime=mime, folder=folder
        )
        return path, public, data
